In [3]:
import pandas as pd

In [1]:
import sys
# Prints the absolute path of the executable binary
print("Interpreter Path:", sys.executable)

# Prints the detailed version info
print("Python Version:", sys.version)

Interpreter Path: c:\Users\User\Desktop\ETAI\ETAI-Pipeline\venv\Scripts\python.exe
Python Version: 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]

In [6]:
df = pd.read_csv('../data/compas_two_year_recidivism.csv')

In [7]:
df

,juv_other_count,score_text,priors_count,juv_misd_count,juvenile_total,sex,age_cat,id,c_charge_degree,two_year_recid,juv_fel_count,age_in_months,race,prior_offenses,age,decile_score
0,1,Low,0.0,0,1.0,Male,25 - 45,8423,F,0,0.0,324.0,African-American,0.0,27.0,2
1,0,High,3.0,0,0.0,Male,Less than 25,4137,M,1,0.0,276.0,Caucasian,3.0,23.0,8
2,0,Low,2.0,0,0.0,male,25 - 45,5064,F,1,0.0,336.0,Caucasian,2.0,28.0,2
3,0,High,2.0,0,0.0,female,Less than 25,56,F,0,NaN,252.0,African-American,2.0,21.0,8
4,0,Low,1.0,0,0.0,Male,25 - 45,9369,M,0,0.0,372.0,African-American,1.0,31.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0,Medium,0.0,0,0.0,Male,Less than 25,1685,f,1,0.0,288.0,Hispanic,0.0,24.0,6
7282,0,Low,3.0,0,0.0,Male,25 - 45,616,F,0,0.0,384.0,African-American,3.0,32.0,2
7283,0,Low,3.0,0,0.0,Male,Greater than 45,5394,F,0,0.0,672.0,-,3.0,56.0,2
7284,0,Low,1.0,0,0.0,Male,25 - 45,2422,F,0,0.0,324.0,African-American,1.0,27.0,2
7285,0,Medium,0.0,0,0.0,Male,Less than 25,8606,NaN,1,0.0,288.0,African-American,0.0,24.0,7

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7286 entries, 0 to 7285
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   juv_other_count  7286 non-null   int64
 1   score_text       7286 non-null   str
 2   priors_count     6866 non-null   str
 3   juv_misd_count   7286 non-null   int64
 4   juvenile_total   7286 non-null   float64
 5   sex              7226 non-null   str
 6   age_cat          7286 non-null   str
 7   id               7286 non-null   int64
 8   c_charge_degree  7053 non-null   str
 9   two_year_recid   7286 non-null   int64
 10  juv_fel_count    7069 non-null   float64
 11  age_in_months    7140 non-null   float64
 12  race             7286 non-null   str
 13  prior_offenses   6866 non-null   str
 14  age              7140 non-null   float64
 15  decile_score     7286 non-null   int64
dtypes: float64(4), int64(5), str(7)
memory usage: 910.9 KB

In [10]:
for col in df.columns:
    print(col, sum(df[col].isnull()))

juv_other_count 0
score_text 0
priors_count 420
juv_misd_count 0
juvenile_total 0
sex 60
age_cat 0
id 0
c_charge_degree 233
two_year_recid 0
juv_fel_count 217
age_in_months 146
race 0
prior_offenses 420
age 146
decile_score 0

In [11]:
df.describe()

,juv_other_count,juv_misd_count,juvenile_total,id,two_year_recid,juv_fel_count,age_in_months,age,decile_score
count,7286.000000,7286.000000,7286.000000,7286.000000,7286.000000,7069.000000,7140.000000,7140.000000,7286.000000
mean,0.109662,0.090585,0.265852,5499.579193,0.451139,0.067619,417.203361,34.766947,4.524156
std,0.502209,0.483668,0.950096,3174.414353,0.497641,0.478998,143.352811,11.946068,2.877104
min,0.000000,0.000000,-1.000000,1.000000,0.000000,-1.000000,-36.000000,-3.000000,0.000000
25%,0.000000,0.000000,0.000000,2736.250000,0.000000,0.000000,300.000000,25.000000,2.000000
50%,0.000000,0.000000,0.000000,5507.500000,0.000000,0.000000,372.000000,31.000000,4.000000
75%,0.000000,0.000000,0.000000,8238.500000,1.000000,0.000000,504.000000,42.000000,7.000000
max,17.000000,13.000000,21.000000,11001.000000,1.000000,20.000000,1152.000000,96.000000,23.000000

In [19]:
categorical_columns = df.select_dtypes(include=["object", "category", "str"]).columns
print(categorical_columns)

Index(['score_text', 'priors_count', 'sex', 'age_cat', 'c_charge_degree',
       'race', 'prior_offenses'],
      dtype='str')

In [20]:
for col in df.select_dtypes(include=["object", "category", "str"]).columns:
    print(col, df[col].unique())

score_text <StringArray>
['Low', 'High', 'Medium', 'low', 'medium', 'LOW', 'MEDIUM', 'HIGH', 'high']
Length: 9, dtype: str
priors_count <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
    '-',  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0',
 '17.0', '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0',
 '38.0', '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0',
 '30.0', '35.0', '36.0', '37.0',  '500']
Length: 41, dtype: str
sex <StringArray>
[   'Male',    'male',  'female',  'Female',    'MALE',   ' Male', 'Female ',
       nan,       '?',  'FEMALE']
Length: 10, dtype: str
age_cat <StringArray>
['25 - 45', 'Less than 25', 'Greater than 45']
Length: 3, dtype: str
c_charge_degree <StringArray>
['F', 'M', 'm', 'Misdemeanor', nan, 'Felony', 'f']
Length: 7, dtype: str
race <StringArray>
[ 'African-American',         'Caucasian',                 '?',
          'Hispanic',             'Other',  'african-american',
 ' African-American',          'HISPANIC',         'caucasian',
                 '-',          'hispanic',         'CAUCASIAN',
   'Native American',        ' Caucasian',  'African American',
  'AFRICAN-AMERICAN',             'Asian']
Length: 17, dtype: str
prior_offenses <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
    '-',  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0',
 '17.0', '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0',
 '38.0', '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0',
 '30.0', '35.0', '36.0', '37.0',  '500']
Length: 41, dtype: str

TypeError: 'Series' object is not callable